{% set name = "pyparam" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyparam-{{ version }}.tar.gz
  sha256: 5513742f9668429d42e7b0acaf02c6ae868466b048ff91f1241f0c6d067a0af5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry >=0.12
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - python-simpleconf >=0.5.0,<0.6.0
    - rich >=13.0.0,<14.0.0
    - diot >=0.1.0,<0.2.0

test:
  imports:
    - pyparam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pwwang/pyparam
  summary: Powerful parameter processing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
